/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulangan;

import javax.swing.JOptionPane;

/**
 *
 * @author paymin
 */
public class GUI_Bank extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Bank
     */
    public GUI_Bank() {
        initComponents();
    }
    
    double saldo = 654.664; 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        btEnter = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        bttitik = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        panel2 = new java.awt.Panel();
        btF = new javax.swing.JButton();
        btA = new javax.swing.JButton();
        btB = new javax.swing.JButton();
        btC = new javax.swing.JButton();
        btD = new javax.swing.JButton();
        btE = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfPin = new javax.swing.JTextField();
        panel3 = new java.awt.Panel();
        btF1 = new javax.swing.JButton();
        btA1 = new javax.swing.JButton();
        btB1 = new javax.swing.JButton();
        btC1 = new javax.swing.JButton();
        btD1 = new javax.swing.JButton();
        btE1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panel4 = new java.awt.Panel();
        btF2 = new javax.swing.JButton();
        btA2 = new javax.swing.JButton();
        btB2 = new javax.swing.JButton();
        btC2 = new javax.swing.JButton();
        btD2 = new javax.swing.JButton();
        btE2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSaldo = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        panel5 = new java.awt.Panel();
        btF3 = new javax.swing.JButton();
        btA3 = new javax.swing.JButton();
        btB3 = new javax.swing.JButton();
        btC3 = new javax.swing.JButton();
        btD3 = new javax.swing.JButton();
        btE3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        setor = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        panel6 = new java.awt.Panel();
        btF4 = new javax.swing.JButton();
        btA4 = new javax.swing.JButton();
        btB4 = new javax.swing.JButton();
        btC4 = new javax.swing.JButton();
        btD4 = new javax.swing.JButton();
        btE4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tarik = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        jButton12.setText("1");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        jLabel6.setText("jLabel6");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Rp. 535.665,00");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(51, 51, 51));

        btEnter.setBackground(new java.awt.Color(0, 204, 0));
        btEnter.setText("ENTER");
        btEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnterActionPerformed(evt);
            }
        });

        bt1.setText("1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setText("2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt3.setText("3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        bt6.setText("6");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        bt5.setText("5");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt4.setText("4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        bt7.setText("7");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        bt8.setText("8");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });

        bt9.setText("9");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });

        bt0.setText("0");
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });

        bttitik.setText(".");
        bttitik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttitikActionPerformed(evt);
            }
        });

        jButton14.setText("-");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        btClear.setBackground(new java.awt.Color(255, 255, 0));
        btClear.setText("CLEAR");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        btCancel.setBackground(new java.awt.Color(255, 0, 0));
        btCancel.setText("CANCEL");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(bttitik, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bt0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btClear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttitik, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(panel1);
        panel1.setBounds(450, 10, 260, 280);

        panel2.setBackground(new java.awt.Color(0, 153, 255));
        panel2.setForeground(new java.awt.Color(255, 255, 255));
        panel2.setLayout(null);
        panel2.add(btF);
        btF.setBounds(360, 200, 60, 40);

        btA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAActionPerformed(evt);
            }
        });
        panel2.add(btA);
        btA.setBounds(0, 100, 60, 40);
        panel2.add(btB);
        btB.setBounds(0, 150, 60, 40);
        panel2.add(btC);
        btC.setBounds(0, 200, 60, 40);

        btD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDActionPerformed(evt);
            }
        });
        panel2.add(btD);
        btD.setBounds(360, 100, 60, 40);

        btE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEActionPerformed(evt);
            }
        });
        panel2.add(btE);
        btE.setBounds(360, 150, 60, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SELAMAT DATANG");
        panel2.add(jLabel3);
        jLabel3.setBounds(90, 20, 230, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DI ANJUNGAN TUNAI MANDIRI");
        panel2.add(jLabel4);
        jLabel4.setBounds(50, 50, 310, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BANK TELKOM MALANG");
        panel2.add(jLabel1);
        jLabel1.setBounds(50, 80, 310, 40);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MASUKKAN PIN");
        panel2.add(jLabel7);
        jLabel7.setBounds(130, 160, 140, 20);

        tfPin.setEditable(false);
        tfPin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel2.add(tfPin);
        tfPin.setBounds(140, 190, 120, 30);

        getContentPane().add(panel2);
        panel2.setBounds(10, 10, 420, 280);

        panel3.setBackground(new java.awt.Color(0, 153, 255));
        panel3.setLayout(null);

        btF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btF1ActionPerformed(evt);
            }
        });
        panel3.add(btF1);
        btF1.setBounds(360, 200, 60, 40);

        btA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btA1ActionPerformed(evt);
            }
        });
        panel3.add(btA1);
        btA1.setBounds(0, 100, 60, 40);

        btB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btB1ActionPerformed(evt);
            }
        });
        panel3.add(btB1);
        btB1.setBounds(0, 150, 60, 40);

        btC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btC1ActionPerformed(evt);
            }
        });
        panel3.add(btC1);
        btC1.setBounds(0, 200, 60, 40);

        btD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btD1ActionPerformed(evt);
            }
        });
        panel3.add(btD1);
        btD1.setBounds(360, 100, 60, 40);

        btE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btE1ActionPerformed(evt);
            }
        });
        panel3.add(btE1);
        btE1.setBounds(360, 150, 60, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PILIH MENU");
        panel3.add(jLabel5);
        jLabel5.setBounds(140, 30, 120, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("<- INFORMASI SALDO");
        panel3.add(jLabel9);
        jLabel9.setBounds(60, 110, 140, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("<- Rp. 100.000 ");
        panel3.add(jLabel11);
        jLabel11.setBounds(60, 160, 140, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("<- Rp. 200.000 ");
        panel3.add(jLabel12);
        jLabel12.setBounds(60, 210, 140, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("PENYETORAN - > ");
        panel3.add(jLabel13);
        jLabel13.setBounds(240, 110, 120, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("PENARIKAN JUMLAH LAIN - > ");
        panel3.add(jLabel14);
        jLabel14.setBounds(170, 160, 190, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("KELUAR - > ");
        panel3.add(jLabel10);
        jLabel10.setBounds(170, 210, 190, 20);

        getContentPane().add(panel3);
        panel3.setBounds(10, 10, 420, 280);

        panel4.setBackground(new java.awt.Color(0, 153, 255));
        panel4.setName(""); // NOI18N
        panel4.setLayout(null);

        btF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btF2ActionPerformed(evt);
            }
        });
        panel4.add(btF2);
        btF2.setBounds(360, 200, 60, 40);

        btA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btA2ActionPerformed(evt);
            }
        });
        panel4.add(btA2);
        btA2.setBounds(0, 100, 60, 40);

        btB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btB2ActionPerformed(evt);
            }
        });
        panel4.add(btB2);
        btB2.setBounds(0, 150, 60, 40);

        btC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btC2ActionPerformed(evt);
            }
        });
        panel4.add(btC2);
        btC2.setBounds(0, 200, 60, 40);

        btD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btD2ActionPerformed(evt);
            }
        });
        panel4.add(btD2);
        btD2.setBounds(360, 100, 60, 40);

        btE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btE2ActionPerformed(evt);
            }
        });
        panel4.add(btE2);
        btE2.setBounds(360, 150, 60, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("LANJUTKAN TRANSAKSI - > ");
        panel4.add(jLabel16);
        jLabel16.setBounds(170, 160, 190, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("KELUAR - > ");
        panel4.add(jLabel15);
        jLabel15.setBounds(170, 210, 190, 20);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("\" Rajin pangkal pandai, menabung pangkal kaya\"");
        panel4.add(jLabel17);
        jLabel17.setBounds(60, 250, 330, 20);

        jSaldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSaldo.setForeground(new java.awt.Color(255, 255, 255));
        jSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jSaldo.setText("Rp. 32143432");
        panel4.add(jSaldo);
        jSaldo.setBounds(130, 100, 150, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("SALDO ANDA");
        panel4.add(jLabel23);
        jLabel23.setBounds(120, 70, 180, 22);

        getContentPane().add(panel4);
        panel4.setBounds(10, 10, 420, 280);

        panel5.setBackground(new java.awt.Color(0, 153, 255));
        panel5.setName(""); // NOI18N
        panel5.setLayout(null);

        btF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btF3ActionPerformed(evt);
            }
        });
        panel5.add(btF3);
        btF3.setBounds(360, 200, 60, 40);

        btA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btA3ActionPerformed(evt);
            }
        });
        panel5.add(btA3);
        btA3.setBounds(0, 100, 60, 40);

        btB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btB3ActionPerformed(evt);
            }
        });
        panel5.add(btB3);
        btB3.setBounds(0, 150, 60, 40);

        btC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btC3ActionPerformed(evt);
            }
        });
        panel5.add(btC3);
        btC3.setBounds(0, 200, 60, 40);

        btD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btD3ActionPerformed(evt);
            }
        });
        panel5.add(btD3);
        btD3.setBounds(360, 100, 60, 40);

        btE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btE3ActionPerformed(evt);
            }
        });
        panel5.add(btE3);
        btE3.setBounds(360, 150, 60, 40);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("KELUAR - > ");
        panel5.add(jLabel19);
        jLabel19.setBounds(170, 210, 190, 20);

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("\" Rajin pangkal pandai, menabung pangkal kaya\"");
        panel5.add(jLabel20);
        jLabel20.setBounds(30, 250, 350, 20);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("SETOR SEBESAR");
        panel5.add(jLabel24);
        jLabel24.setBounds(120, 70, 180, 22);

        setor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        setor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setorActionPerformed(evt);
            }
        });
        panel5.add(setor);
        setor.setBounds(120, 100, 180, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("SETOR - >");
        panel5.add(jLabel18);
        jLabel18.setBounds(160, 160, 190, 20);

        getContentPane().add(panel5);
        panel5.setBounds(10, 10, 420, 280);

        panel6.setBackground(new java.awt.Color(0, 153, 255));
        panel6.setForeground(new java.awt.Color(255, 255, 255));
        panel6.setName(""); // NOI18N
        panel6.setLayout(null);

        btF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btF4ActionPerformed(evt);
            }
        });
        panel6.add(btF4);
        btF4.setBounds(360, 200, 60, 40);

        btA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btA4ActionPerformed(evt);
            }
        });
        panel6.add(btA4);
        btA4.setBounds(0, 100, 60, 40);

        btB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btB4ActionPerformed(evt);
            }
        });
        panel6.add(btB4);
        btB4.setBounds(0, 150, 60, 40);

        btC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btC4ActionPerformed(evt);
            }
        });
        panel6.add(btC4);
        btC4.setBounds(0, 200, 60, 40);

        btD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btD4ActionPerformed(evt);
            }
        });
        panel6.add(btD4);
        btD4.setBounds(360, 100, 60, 40);

        btE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btE4ActionPerformed(evt);
            }
        });
        panel6.add(btE4);
        btE4.setBounds(360, 150, 60, 40);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("KELUAR - > ");
        panel6.add(jLabel21);
        jLabel21.setBounds(170, 210, 190, 20);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("\" Rajin pangkal pandai, menabung pangkal kaya\"");
        panel6.add(jLabel22);
        jLabel22.setBounds(30, 250, 350, 20);

        tarik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tarik.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarikActionPerformed(evt);
            }
        });
        panel6.add(tarik);
        tarik.setBounds(120, 100, 180, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("TARIK TUNAI SEBESAR");
        panel6.add(jLabel25);
        jLabel25.setBounds(120, 70, 180, 22);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("TARIK - >");
        panel6.add(jLabel26);
        jLabel26.setBounds(170, 160, 190, 20);

        getContentPane().add(panel6);
        panel6.setBounds(10, 10, 420, 280);

        setBounds(0, 0, 732, 342);
    }// </editor-fold>//GEN-END:initComponents

    private void btEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnterActionPerformed
        // TODO add your handling code here:
        String nomer = tfPin.getText();
        if(nomer.equals("1234")){
            panel3.setVisible(true);
            panel2.setVisible(false);
            tfPin.setText("");
            tarik.setText("");
        } else {
            tfPin.setText("");
        }
          
        
    }//GEN-LAST:event_btEnterActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        String nomer, nyetor;
        nomer = tfPin.getText() + bt1.getText();
        tfPin.setText(nomer);
        nyetor = setor.getText() + bt1.getText();
        setor.setText(nyetor);
        
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        String nomer, nyetor;
        nomer = tfPin.getText() + bt2.getText();
        tfPin.setText(nomer);
        nyetor = setor.getText() + bt2.getText();
        setor.setText(nyetor);
        
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        String nomer, nyetor;
        nomer = tfPin.getText() + bt3.getText();
        tfPin.setText(nomer);
        nyetor = setor.getText() + bt3.getText();
        setor.setText(nyetor);
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        // TODO add your handling code here:
        String nomer, nyetor;
        nomer = tfPin.getText() + bt6.getText();
        tfPin.setText(nomer);
        nyetor = setor.getText() + bt6.getText();
        setor.setText(nyetor);
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        // TODO add your handling code here:
        String nomer, nyetor;
        nomer = tfPin.getText() + bt5.getText();
        tfPin.setText(nomer);
        nyetor = setor.getText() + bt5.getText();
        setor.setText(nyetor);
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // TODO add your handling code here:
        String nomer, nyetor;
        nomer = tfPin.getText() + bt4.getText();
        tfPin.setText(nomer);
        nyetor = setor.getText() + bt4.getText();
        setor.setText(nyetor);
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        // TODO add your handling code here:
        String nomer, nyetor;
        nomer = tfPin.getText() + bt7.getText();
        tfPin.setText(nomer);
        nyetor = setor.getText() + bt7.getText();
        setor.setText(nyetor);
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        // TODO add your handling code here:
        String nomer, nyetor;
        nomer = tfPin.getText() + bt8.getText();
        tfPin.setText(nomer);
        nyetor = setor.getText() + bt8.getText();
        setor.setText(nyetor);
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        // TODO add your handling code here:
        String nomer, nyetor;
        nomer = tfPin.getText() + bt9.getText();
        tfPin.setText(nomer);
        nyetor = setor.getText() + bt9.getText();
        setor.setText(nyetor);
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        // TODO add your handling code here:
        String nomer,nyetor;
        nomer = tfPin.getText() + bt0.getText();
        tfPin.setText(nomer);
        nyetor = setor.getText() + bt0.getText();
        setor.setText(nyetor);
    }//GEN-LAST:event_bt0ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void bttitikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttitikActionPerformed
        // TODO add your handling code here:
        String nyetor;
        nyetor = setor.getText() + bttitik.getText();
        setor.setText(nyetor);
    }//GEN-LAST:event_bttitikActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
        tfPin.setText("");
        setor.setText("");
    }//GEN-LAST:event_btClearActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        panel3.setVisible(true);
    }//GEN-LAST:event_btCancelActionPerformed

    private void btDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDActionPerformed
        // TODO add your handling code here:
        panel5.setVisible(true);
        panel4.setVisible(false);
        panel3.setVisible(false);
        
        
    }//GEN-LAST:event_btDActionPerformed

    private void btD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btD1ActionPerformed
        // TODO add your handling code here:
        panel5.setVisible(true);
        panel3.setVisible(false);
        panel4.setVisible(false);
        
    }//GEN-LAST:event_btD1ActionPerformed

    private void btA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btA1ActionPerformed
        // TODO add your handling code here:
        panel4.setVisible(true);
        panel3.setVisible(false);
        
        jSaldo.setText("Rp. " + saldo + ",-");
    }//GEN-LAST:event_btA1ActionPerformed

    private void btB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btB1ActionPerformed
        // TODO add your handling code here:
        panel2.setVisible(false);
    }//GEN-LAST:event_btB1ActionPerformed

    private void btC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btC1ActionPerformed
        // TODO add your handling code here:
        panel2.setVisible(false);
    }//GEN-LAST:event_btC1ActionPerformed

    private void btE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btE1ActionPerformed
        // TODO add your handling code here:
        panel6.setVisible(true);
        panel3.setVisible(false);
        panel4.setVisible(false);
        panel5.setVisible(false);
    }//GEN-LAST:event_btE1ActionPerformed

    private void btF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btF1ActionPerformed
        // TODO add your handling code here:
        panel2.setVisible(true);
        panel3.setVisible(false);
        
    }//GEN-LAST:event_btF1ActionPerformed

    private void btF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btF2ActionPerformed
        // TODO add your handling code here:
        panel4.setVisible(false);
        panel3.setVisible(true);
    }//GEN-LAST:event_btF2ActionPerformed

    private void btA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btA2ActionPerformed

    private void btB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btB2ActionPerformed

    private void btC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btC2ActionPerformed

    private void btD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btD2ActionPerformed

    private void btE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btE2ActionPerformed
        // TODO add your handling code here:
        panel3.setVisible(true);
        panel4.setVisible(false);
    }//GEN-LAST:event_btE2ActionPerformed

    private void btF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btF3ActionPerformed
        // TODO add your handling code here:
        panel5.setVisible(false);
        panel3.setVisible(true);
    }//GEN-LAST:event_btF3ActionPerformed

    private void btA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btA3ActionPerformed

    private void btB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btB3ActionPerformed

    private void btC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btC3ActionPerformed

    private void btD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btD3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btD3ActionPerformed

    private void btE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btE3ActionPerformed
        // TODO add your handling code here:
            panel5.setVisible(false);
            panel3.setVisible(true);
            saldo = saldo + Double.parseDouble(setor.getText());
    }//GEN-LAST:event_btE3ActionPerformed

    private void setorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setorActionPerformed

    private void btF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btF4ActionPerformed
        // TODO add your handling code here:
        panel6.setVisible(false);
        panel3.setVisible(true);
    }//GEN-LAST:event_btF4ActionPerformed

    private void btA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btA4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btA4ActionPerformed

    private void btB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btB4ActionPerformed

    private void btC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btC4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btC4ActionPerformed

    private void btD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btD4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btD4ActionPerformed

    private void btE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btE4ActionPerformed
        // TODO add your handling code here:
        saldo = saldo - Double.parseDouble(tarik.getText());
        
        panel3.setVisible(true);
        panel6.setVisible(false);
        
    }//GEN-LAST:event_btE4ActionPerformed

    private void tarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarikActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_tarikActionPerformed

    private void btEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEActionPerformed
        // TODO add your handling code here:
        panel6.setVisible(true);
        panel3.setVisible(false);
        panel5.setVisible(false);
        panel4.setVisible(false);
        
    }//GEN-LAST:event_btEActionPerformed

    private void btAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAActionPerformed
        // TODO add your handling code here:
        panel4.setVisible(true);
        panel3.setVisible(false);
    }//GEN-LAST:event_btAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Bank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btA;
    private javax.swing.JButton btA1;
    private javax.swing.JButton btA2;
    private javax.swing.JButton btA3;
    private javax.swing.JButton btA4;
    private javax.swing.JButton btB;
    private javax.swing.JButton btB1;
    private javax.swing.JButton btB2;
    private javax.swing.JButton btB3;
    private javax.swing.JButton btB4;
    private javax.swing.JButton btC;
    private javax.swing.JButton btC1;
    private javax.swing.JButton btC2;
    private javax.swing.JButton btC3;
    private javax.swing.JButton btC4;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btD;
    private javax.swing.JButton btD1;
    private javax.swing.JButton btD2;
    private javax.swing.JButton btD3;
    private javax.swing.JButton btD4;
    private javax.swing.JButton btE;
    private javax.swing.JButton btE1;
    private javax.swing.JButton btE2;
    private javax.swing.JButton btE3;
    private javax.swing.JButton btE4;
    private javax.swing.JButton btEnter;
    private javax.swing.JButton btF;
    private javax.swing.JButton btF1;
    private javax.swing.JButton btF2;
    private javax.swing.JButton btF3;
    private javax.swing.JButton btF4;
    private javax.swing.JButton bttitik;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jSaldo;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    private javax.swing.JTextField setor;
    private javax.swing.JTextField tarik;
    private javax.swing.JTextField tfPin;
    // End of variables declaration//GEN-END:variables
}
